### PR TITLE
Closing issue #12 - Update NOOVO stream

### PR DESCRIPTION
**Pull request by alegag**
Add new stream-link for NOOVO, thanks to Sphinxroot for finding it out.

### CODE REVIEW

**Comment by alegag** [comment]
Anything preventing this branch from being merged ? @geonsey

**Comment by geonsey** [comment]
> Anything preventing this branch from being merged ? @geonsey

Not that I am aware of... but I don't want my original list to be affected by any... 'merges' (dunno how that really works or affects things here, honestly-- educate me, perhaps lol)... but unless there's a working m3u8 for Noovo, I will be removing it from the main playlist anyways.

**Comment by geonsey** [comment]
Closed issue #12.

**Comment by mikhoul** [comment]
> unless there's a working m3u8 for Noovo, I will be removing it from the main playlist anyways.

Why do you remove it ?  🤔

It work in 99.9% of the IPTV players available on all platforms.

**Comment by geonsey** [comment]
> > unless there's a working m3u8 for Noovo, I will be removing it from the main playlist anyways.
> 
> Why do you remove it ? 🤔
> 
> It work in 99.9% of the IPTV players available on all platforms.

Hmmm. What's the stream URL that works for you guys?

**Comment by mikhoul** [comment]
This URL: https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd

It's an MPD file,  you can insert it inside a M3U file as the source.

Regards :octocat:

**Comment by alegag** [comment]
> Not that I am aware of... but I don't want my original list to be affected by any... 'merges' (dunno how that really works or affects things here, honestly-- educate me, perhaps lol)...

Well, you can click on the "Files changed" tab at the top of this PR and you will see what I have change.  And you'll see that it is limited to the Noovo channel.  If you merge this, the file in this repo will be updated, and you will simply have to download it again to your environment (or do a `git pull` in your IDE of choice).

That shouldn't "overwrite" your files or break anything, it will only apply my change that fixes the non-working Noovo link.

This is pretty much the idea of Git with collaboration, that someone helps you with an update your can validate and migrate back in your project.  That don't give me access to anything.

> but unless there's a working m3u8 for Noovo, I will be removing it from the main playlist anyways.

The MDP links works just fine, I don't think we need to setup a proxy server that would have a converted M3U8 for that.

You will see in my update that I have two hash-tags above the MDP link.  It makes it work on Kodi, it don't break the rest.  I'm using it since Sphinxroot kindly provided that in the issue #12 

I really think we are better off with that solution (the three lines I added/replaced) than no Noovo channel at all.  This is one of the big-four free-channels for the Quebec market, I think that would be a big missing part if it was to be removed completely while a working solution exists.

**Comment by geonsey** [comment]
@alegag so this has been helpful... merged the files and the link seems to work great in Perfect Player. Question: 

#EXTINF:-1 tvg-logo="https://github.com/geonsey/Free2ViewTV/blob/master/images/logos/Noovo_608x608.png?raw=true" group-title="Canadian TV",noovo
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd

The #KodiProp tag... what exactly does that do?

**Comment by mikhoul** [comment]
> The #KodiProp tag... what exactly does that do?

Kodi use a plug-in to play MPD stream so it need to be aware of MPD stream to use the plugin instead of using the core decoder.

Other players don't read the tags so they interpret them as "comments".

**Comment by geonsey** [comment]
@mikhoul very interesting. Well, you guys taught me something new. 
If any of you are interested in joining our Discord community, all of you will be welcomed. 
Here's an invite: https://discord.gg/C48WhSTpw7
Hope to see you there.

**Pull request merged**
